configure: explicitly depend on gio-2.0
Linkers from the future get upset, with messages like:

  /usr/bin/ld: ./.libs/libidle-convenience.a(idle-server-connection.o):
    undefined reference to symbol 'g_io_stream_get_output_stream'
  /usr/bin/ld: note: 'g_io_stream_get_output_stream' is defined in DSO
    /usr/lib/libgio-2.0.so.0 so try adding it to the linker command line
  /usr/lib/libgio-2.0.so.0: could not read symbols: Invalid operation

So we need to explicitly depend on it.

While we're here: we certainly don't build against glib 2.4. glib 2.28.0
is the version required by the version of telepathy-glib we require.